# Generated by Django 4.2.3 on 2023-07-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_log_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='data',
            field=models.TextField(),
        ),
    ]
